apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1  # One replica only
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # Can be adjusted
      maxUnavailable: 1  # Controls how many pods can be unavailable during the update
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: hansakatennakoon/notification
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
